name: Build for Windows

on:
  push:
    branches:
      - main
  create: # タグが作成されたときにもトリガーする
    tags:
      - '*'

jobs:
  build-and-run:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy release files
        run: xcopy /s /e /i /y .\release\* .\windows\dist\

      - name: Build Docker image
        run: docker build  -f ./windows/Dockerfile -t python-website-tour-exe-windows .
      
      - name: Run Docker container
        run: docker run --rm  -v ${{ github.workspace }}\windows\dist\:C:\dist\ python-website-tour-exe-windows powershell -Command "pyinstaller main.py --onedir --onefile --clean --distpath /dist --workpath /windows/build --specpath /windows"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python_website_tour_exe
          path: ./windows/dist/
